export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
# export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
# export HOMEBREW_UPDATE_PREINSTALL=0

# export ANYENV_DEBUG=1

export LOCAL="${HOME}/.local"
export LOCALOPT="${LOCAL}/opt"

export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${LOCAL}/share"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_STATE_HOME="${LOCAL}/state"
export XDG_LOG_HOME="${LOCAL}/var/log"

export ANDROID_HOME="${XDG_DATA_HOME}/android"
export ANYENV_ROOT="${LOCALOPT}/anyenv"
export ANSIBLE_HOME="${XDG_CONFIG_HOME}/ansible"
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME}/ansible/ansible.cfg"
export ANSIBLE_GALAXY_CACHE_DIR="${XDG_CACHE_HOME}/ansible/galaxy_cache"
export BASH_COMPLETION_USER_FILE="${XDG_CONFIG_HOME}/bash-completion/bash_completion"
export BUNDLE_USER_CONFIG="${XDG_CONFIG_HOME}/bundle"
export BUNDLE_USER_CACHE="${XDG_CACHE_HOME}/bundle"
export BUNDLE_USER_PLUGIN="${XDG_DATA_HOME}/bundle"
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export CONDARC="${XDG_CONFIG_HOME}/conda/condarc"
# export DOCKER_CONFIG="${XDG_CONFIG_HOME}/docker"
# export MACHINE_STORAGE_PATH="${XDG_DATA_HOME}/docker-machine"
export FFMPEG_DATADIR="${XDG_CONFIG_HOME}/ffmpeg"
# export GNUPGHOME="${XDG_DATA_HOME}/gnupg"
export GDBHISTFILE="${XDG_DATA_HOME}/gdb/history"
export GEM_HOME="${XDG_DATA_HOME}/gem"
export GEM_SPEC_CACHE="${XDG_CACHE_HOME}/gem"
export GOPATH="${XDG_DATA_HOME}/go"
export GOMODCACHE="${XDG_CACHE_HOME}/go/mod"
export GRADLE_USER_HOME="${XDG_DATA_HOME}/gradle"
export GTK_RC_FILES="${XDG_CONFIG_HOME}/gtk-1.0/gtkrc"
export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc"
export HELM_HOME="${XDG_DATA_HOME}/helm"
export _JAVA_OPTIONS='-Djava.util.prefs.userRoot="${XDG_CONFIG_HOME}/java" -Djavafx.cachedir="${XDG_CACHE_HOME}/openjfx"'
export JAVA_TOOL_OPTIONS='-Djava.util.prefs.userRoot="${XDG_CONFIG_HOME}/java" -Djavafx.cachedir="${XDG_CACHE_HOME}/openjfx"'
export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME}/jupyter"
export JUPYTER_PLATFORM_DIRS="1"
export KUBECONFIG="${XDG_CONFIG_HOME}/kube/config"
export KUBECACHEDIR="${XDG_CACHE_HOME}/kube"
export MINIKUBE_HOME="${XDG_DATA_HOME}/minikube"
export MYPY_CACHE_DIR="${XDG_CACHE_HOME}/mypy"
export MYSQL_HISTFILE="${XDG_DATA_HOME}/mysql/history"
export NODE_REPL_HISTORY="${XDG_DATA_HOME}/node/repl_history"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/config"
export NPM_CONFIG_CACHE="${XDG_CACHE_HOME}/npm"
export OCI_CLI_AUTH='security_token'
export OCI_AUTO_PROMPT='True'
export OCI_CLI_PROFILE='SESSION'
# export OCI_CONFIG_FILE="${HOME}/Library/Application Support/oci/config"
# export OCI_CLI_CONFIG_FILE="${HOME}/Library/Application Support/oci/config"
# export OCI_CLI_RC_FILE="${HOME}/Library/Application Support/oci/oci_cli_rc"
export POETRY_HOME="${LOCALOPT}/poetry"
export PYLINTHOME="${XDG_CACHE_HOME}/pylint"
export PYLINTRC="${XDG_CONFIG_HOME}/pylint/config"
export PYTHONPYCACHEPREFIX="${XDG_CACHE_HOME}/python"
export PYTHONSTARTUP="${XDG_CONFIG_HOME}/python/pythonrc"
export PYTHONUSERBASE="${XDG_DATA_HOME}/python"
export PYTHON_EGG_CACHE="${XDG_CACHE_HOME}/python-eggs"
export PLATFORMIO_CORE_DIR="${XDG_DATA_HOME}/platform-io"
export RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME}/ripgrep/config"
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
export SQLITE_HISTORY="${XDG_DATA_HOME}/sqlite/history"
export VIMINIT="source ${XDG_CONFIG_HOME}/vim/vimrc"
# export VIMINIT="set nocp | source ${XDG_CONFIG_HOME}/vim/vimrc"
export WGETRC="${XDG_CONFIG_HOME}/wget/config"
# export XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

export MAKE_OPTS="-j$(sysctl -n hw.logicalcpu_max)"

alias sbt='sbt -ivy "${XDG_DATA_HOME}/ivy2" -sbt-dir "${XDG_DATA_HOME}/sbt"'
alias yarn='yarn --use-yarnrc "${XDG_CONFIG_HOME}/yarn/config"'

. "${XDG_DATA_HOME}/cargo/env"
