export HOMEBREW_NO_AUTO_UPDATE=1
# export ANYENV_DEBUG=1

export LOCAL="${HOME}/.local"
export LOCALOPT="${LOCAL}/opt"

export XDG_CONFIG_HOME="${LOCAL}/etc"
export XDG_DATA_HOME="${LOCAL}/share"
export XDG_CACHE_HOME="${LOCAL}/var/cache"
export XDG_STATE_HOME="${LOCAL}/state"
export XDG_LOG_HOME="${LOCAL}/var/log"

export ANYENV_ROOT="${LOCALOPT}/anyenv"
export BUNDLE_USER_CONFIG="${XDG_CONFIG_HOME}/bundle"
export BUNDLE_USER_CACHE="${XDG_CACHE_HOME}/bundle"
export BUNDLE_USER_PLUGIN="${XDG_DATA_HOME}/bundle"
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export CONDARC="$XDG_CONFIG_HOME/conda/condarc"
# export DOCKER_CONFIG="${XDG_CONFIG_HOME}/docker"
export GDBHISTFILE="${XDG_DATA_HOME}/gdb/history"
export GEM_HOME="${XDG_DATA_HOME}/gem"
export GEM_SPEC_CACHE="${XDG_CACHE_HOME}/gem"
export GOPATH="${XDG_DATA_HOME}/go"
export GRADLE_USER_HOME="${XDG_DATA_HOME}/gradle"
# export HISTFILE="${XDG_STATE_HOME}/zsh/history"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="${XDG_CONFIG_HOME}/java"
export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME}/jupyter"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/config"
export NPM_CONFIG_CACHE="${XDG_CACHE_HOME}/npm"
export PROTOBUF_ROOT="${LOCALOPT}/protobuf"
export PYTHON_EGG_CACHE="${XDG_CACHE_HOME}/python-eggs"
export RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME}/ripgrep/config"
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
# export XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority"

export MAKE_OPTS="-j$(sysctl -n hw.logicalcpu_max)"

alias sbt='sbt -ivy "${XDG_DATA_HOME}/ivy2" -sbt-dir "${XDG_DATA_HOME}/sbt"'
alias yarn='yarn --use-yarnrc "${XDG_CONFIG_HOME}/yarn/config"'

. "${XDG_DATA_HOME}/cargo/env"
