export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1
export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
export HOMEBREW_UPDATE_PREINSTALL=0

# export ANYENV_DEBUG=1

export LOCAL="${HOME}/.local"
export LOCALOPT="${LOCAL}/opt"

export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_DATA_HOME="${LOCAL}/share"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_STATE_HOME="${LOCAL}/state"
export XDG_LOG_HOME="${LOCAL}/var/log"

export ANYENV_ROOT="${LOCALOPT}/anyenv"
export BUNDLE_USER_CONFIG="${XDG_CONFIG_HOME}/bundle"
export BUNDLE_USER_CACHE="${XDG_CACHE_HOME}/bundle"
export BUNDLE_USER_PLUGIN="${XDG_DATA_HOME}/bundle"
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export CONDARC="${XDG_CONFIG_HOME}/conda/condarc"
# export DOCKER_CONFIG="${XDG_CONFIG_HOME}/docker"
# export MACHINE_STORAGE_PATH="${XDG_DATA_HOME}/docker-machine"
export GDBHISTFILE="${XDG_DATA_HOME}/gdb/history"
export GEM_HOME="${XDG_DATA_HOME}/gem"
export GEM_SPEC_CACHE="${XDG_CACHE_HOME}/gem"
export GOPATH="${XDG_DATA_HOME}/go"
export GRADLE_USER_HOME="${XDG_DATA_HOME}/gradle"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="${XDG_CONFIG_HOME}/java"
export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME}/jupyter"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/config"
export NPM_CONFIG_CACHE="${XDG_CACHE_HOME}/npm"

export POETRY_HOME="${LOCALOPT}/poetry"
export PYTHON_EGG_CACHE="${XDG_CACHE_HOME}/python-eggs"
export PLATFORMIO_CORE_DIR="${XDG_DATA_HOME}/platform-io"
export RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME}/ripgrep/config"
export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
export VIMINIT="set nocp | source ${XDG_CONFIG_HOME}/vim/vimrc"
# export XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

export MAKE_OPTS="-j$(sysctl -n hw.logicalcpu_max)"

alias sbt='sbt -ivy "${XDG_DATA_HOME}/ivy2" -sbt-dir "${XDG_DATA_HOME}/sbt"'
alias yarn='yarn --use-yarnrc "${XDG_CONFIG_HOME}/yarn/config"'

. "${XDG_DATA_HOME}/cargo/env"
